CREATE Table IF NOT EXISTS Etudiant (id INTEGER PRIMARY KEY AUTOINCREMENT,nom TEXT,class TEXT,mark TEXT);
INSERT or IGNORE INTO Etudiant VALUES (1,'Baye','L3GL','BL3GL12'); 
INSERT or IGNORE INTO Etudiant VALUES (2,'LO','L3RI','LL3RI12');
INSERT or IGNORE INTO Etudiant VALUES (3,'Seck','L3GL','SL3GL12');
